# Generated by Django 5.2.1 on 2025-05-22 03:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=200)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('duracion', models.DecimalField(decimal_places=0, max_digits=5)),
                ('avance', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Avance')),
                ('estado', models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], default='no_iniciado', max_length=20)),
                ('predecesoras', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('adjuntos', models.FileField(blank=True, upload_to='actividades/adjuntos/')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_herramienta', models.CharField(max_length=200, verbose_name='Material o Herramienta')),
                ('unidad', models.CharField(max_length=50)),
                ('proyecto', models.CharField(max_length=200)),
                ('actividad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('centro_costos', models.CharField(max_length=100, verbose_name='Centro de Costos')),
                ('nombre_proyecto', models.CharField(max_length=200, verbose_name='Nombre Proyecto')),
                ('orden_contrato', models.CharField(max_length=100, verbose_name='Orden o Contrato')),
                ('dias_prometidos', models.PositiveIntegerField(verbose_name='Promesa de Días')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('avance', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Avance')),
                ('observaciones', models.TextField(blank=True)),
                ('adjunto', models.FileField(blank=True, upload_to='proyectos/adjuntos/')),
                ('cotizacion', models.FileField(blank=True, upload_to='proyectos/legalizacion/', verbose_name='1.0) Oferta')),
                ('orden_compra', models.FileField(blank=True, upload_to='proyectos/legalizacion/', verbose_name='1.1) Orden de Compra')),
                ('contrato', models.FileField(blank=True, upload_to='proyectos/legalizacion/', verbose_name='1.2) Contrato')),
                ('polizas', models.FileField(blank=True, upload_to='proyectos/legalizacion/', verbose_name='1.3) Pólizas')),
                ('correo_formalizacion', models.TextField(blank=True, verbose_name='1.4) Correo o Formalización')),
                ('acta_socializacion', models.FileField(blank=True, upload_to='proyectos/legalizacion/', verbose_name='1.5) Acta de Socialización')),
                ('cronograma', models.FileField(blank=True, upload_to='proyectos/planeacion/', verbose_name='2.0) Cronograma')),
                ('acta_inicio', models.FileField(blank=True, upload_to='proyectos/planeacion/', verbose_name='2.1) Acta de Inicio')),
                ('inspeccion_hseq', models.FileField(blank=True, upload_to='proyectos/planeacion/', verbose_name='2.2) Inspección Condiciones HSEQ')),
                ('inspeccion_propiedad_cliente', models.FileField(blank=True, upload_to='proyectos/planeacion/', verbose_name='2.3) Inspección Propiedad del Cliente')),
                ('control_cambios', models.FileField(blank=True, upload_to='proyectos/ejecucion/', verbose_name='3.0) Control de Cambios')),
                ('acta_avance_obras', models.FileField(blank=True, upload_to='proyectos/ejecucion/', verbose_name='3.1) Acta de avance de obras')),
                ('informes_trabajo', models.FileField(blank=True, upload_to='proyectos/ejecucion/', verbose_name='3.2) Informes de Trabajo')),
                ('informes_control', models.FileField(blank=True, upload_to='proyectos/ejecucion/', verbose_name='3.2.1) Informes de Control')),
                ('informes_mantenimiento', models.FileField(blank=True, upload_to='proyectos/ejecucion/', verbose_name='3.2.2) Informes de Mantenimiento')),
                ('informes_externos', models.FileField(blank=True, upload_to='proyectos/ejecucion/', verbose_name='3.3) Informes Externos')),
                ('informe_tecnico', models.FileField(blank=True, upload_to='proyectos/ejecucion/', verbose_name='3.4) Informe Técnico')),
                ('comunicaciones_cliente', models.FileField(blank=True, upload_to='proyectos/ejecucion/', verbose_name='3.5) Correos - Comunicaciones con el Cliente')),
                ('ficha_diseno', models.FileField(blank=True, upload_to='proyectos/ejecucion/', verbose_name='3.6) Ficha de Diseño')),
                ('remision', models.FileField(blank=True, upload_to='proyectos/entrega/', verbose_name='4.0) Remisión')),
                ('factura', models.FileField(blank=True, upload_to='proyectos/entrega/', verbose_name='4.1) Factura')),
                ('acta_entrega', models.FileField(blank=True, upload_to='proyectos/entrega/', verbose_name='4.2) Acta de Entrega')),
                ('acta_liquidacion', models.FileField(blank=True, upload_to='proyectos/entrega/', verbose_name='4.3) Acta de Liquidación Final')),
                ('acta_cierre', models.FileField(blank=True, upload_to='proyectos/entrega/', verbose_name='4.4) Acta de Cierre')),
                ('archivos_generales', models.FileField(blank=True, upload_to='proyectos/general/')),
                ('trato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecto', to='crm.trato')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, upload_to='entregables/')),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subactividad', models.CharField(max_length=200)),
                ('descripcion', models.TextField(verbose_name='Descripción de la Actividad')),
                ('duracion_horas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Duración (Horas)')),
                ('observaciones', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='bitacora/imagenes/')),
                ('archivo', models.FileField(blank=True, upload_to='bitacora/archivos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='proyectos.actividad')),
                ('equipo', models.ManyToManyField(related_name='bitacoras_equipo', to='proyectos.colaborador')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras_responsable', to='proyectos.colaborador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='proyectos.proyecto'),
        ),
        migrations.CreateModel(
            name='BitacoraRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='proyectos.bitacora')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.recurso')),
            ],
        ),
    ]
