# Generated by Django 5.2.1 on 2025-05-22 13:52

import django.core.validators
import django.db.models.deletion
import proyectos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_add_fecha_creacion_to_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('can_view_all_projects', 'Puede ver todos los proyectos'), ('can_export_projects', 'Puede exportar proyectos')], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('en_revision', 'En Revisión'), ('completado', 'Completado'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización Real'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='gasto_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gasto Real'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto Total'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critico', 'Crítico')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='entregadocumental',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('entregado', 'Entregado')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[proyectos.models.validate_porcentaje], verbose_name='% Avance'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(validators=[proyectos.models.validate_fecha_futura_solo_nuevos], verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='orden_contrato',
            field=models.CharField(max_length=100, unique=True, verbose_name='Orden o Contrato'),
        ),
    ]
