# Generated by Django 5.2.3 on 2025-06-18 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_entregableproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='bitacora/adjuntos/', verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='proyectos.bitacora')),
            ],
            options={
                'verbose_name': 'Archivo de Bitácora',
                'verbose_name_plural': 'Archivos de Bitácora',
                'ordering': ['fecha_subida'],
            },
        ),
    ]
