# Generated by Django 5.2.3 on 2025-06-18 13:56

import proyectos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_alter_proyecto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='avance_planeado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de avance esperado según el cronograma', max_digits=5, validators=[proyectos.models.validate_porcentaje], verbose_name='% Avance Planeado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[proyectos.models.validate_porcentaje], verbose_name='% Avance Real'),
        ),
    ]
