# Generated by Django 5.2.3 on 2025-06-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='director_proyecto',
            field=models.ForeignKey(blank=True, help_text='Colaborador responsable de dirigir el proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_dirigidos', to='proyectos.colaborador', verbose_name='Director de Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ingeniero_residente',
            field=models.ForeignKey(blank=True, help_text='Colaborador responsable de la residencia del proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_residencia', to='proyectos.colaborador', verbose_name='Ingeniero Residente'),
        ),
    ]
