# Generated by Django 5.2.3 on 2025-06-18 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_trato_fecha_creacion'),
        ('proyectos', '0011_add_director_ingeniero_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cotizacion_aprobada',
            field=models.ForeignKey(blank=True, help_text='Cotización aprobada asociada al proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.versioncotizacion', verbose_name='Cotización Aprobada'),
        ),
    ]
