# Generated by Django 5.2.3 on 2025-06-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_add_cotizacion_aprobada'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='responsable_asignado',
            field=models.ForeignKey(blank=True, help_text='Colaborador responsable de ejecutar esta actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_asignadas', to='proyectos.colaborador', verbose_name='Responsable Asignado'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='responsable_ejecucion',
            field=models.CharField(choices=[('rgd', 'RGD Aire'), ('cliente', 'Cliente'), ('externo', 'Tercero/Externo')], default='rgd', help_text='Indica quién ejecuta la actividad: RGD Aire, Cliente o Tercero', max_length=10, verbose_name='Responsable de Ejecución'),
        ),
    ]
