# Generated by Django 5.2.3 on 2025-06-19 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_remove_proyecto_prioridad_alter_proyecto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProrrogaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin_original', models.DateField(verbose_name='Fecha Fin Original')),
                ('fecha_fin_propuesta', models.DateField(verbose_name='Nueva Fecha Fin Propuesta')),
                ('dias_extension', models.PositiveIntegerField(verbose_name='Días de Extensión')),
                ('tipo_prorroga', models.CharField(choices=[('cliente', 'Solicitud del Cliente'), ('tecnica', 'Razón Técnica'), ('clima', 'Condiciones Climáticas'), ('recursos', 'Disponibilidad de Recursos'), ('fuerza_mayor', 'Fuerza Mayor'), ('otra', 'Otra Razón')], max_length=20, verbose_name='Tipo de Prórroga')),
                ('justificacion', models.TextField(verbose_name='Justificación de la Prórroga')),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('aplicada', 'Aplicada')], default='solicitada', max_length=20)),
                ('aprobada_por', models.CharField(blank=True, max_length=200, verbose_name='Aprobada por')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('observaciones_aprobacion', models.TextField(blank=True, verbose_name='Observaciones de Aprobación')),
                ('documento_soporte', models.FileField(blank=True, upload_to='prorrogas/', verbose_name='Documento de Soporte')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prorrogas', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Prórroga de Proyecto',
                'verbose_name_plural': 'Prórrogas de Proyecto',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
