# Generated by Django 5.2.3 on 2025-06-19 21:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_prorrogaproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='dispositivo_firma_director',
            field=models.CharField(blank=True, help_text='Información del dispositivo usado para firmar', max_length=200, verbose_name='Dispositivo Firma Director'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='dispositivo_firma_ingeniero',
            field=models.CharField(blank=True, help_text='Información del dispositivo usado para firmar', max_length=200, verbose_name='Dispositivo Firma Ingeniero'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='estado',
            field=models.CharField(choices=[('planeada', 'Planeada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planeada', help_text='Estado actual de la actividad', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='estado_validacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validada_director', 'Validada por Director'), ('validada_ingeniero', 'Validada por Ingeniero'), ('validada_completa', 'Validación Completa'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Estado de validación por director e ingeniero', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_ejecucion_real',
            field=models.DateField(blank=True, help_text='Fecha en que realmente se ejecutó la actividad', null=True, verbose_name='Fecha de Ejecución Real'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_firma_director',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Firma Director'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_firma_ingeniero',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Firma Ingeniero'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_planificada',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se planificó ejecutar esta actividad', verbose_name='Fecha de Ejecución Planeada'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='firma_director',
            field=models.TextField(blank=True, help_text='Firma digital del director del proyecto', verbose_name='Firma Digital Director'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='firma_ingeniero',
            field=models.TextField(blank=True, help_text='Firma digital del ingeniero residente', verbose_name='Firma Digital Ingeniero'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='ip_firma_director',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se firmó', null=True, verbose_name='IP Firma Director'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='ip_firma_ingeniero',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se firmó', null=True, verbose_name='IP Firma Ingeniero'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='lider_trabajo',
            field=models.ForeignKey(blank=True, help_text='Persona responsable de liderar el equipo en esta actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_lider', to='proyectos.colaborador', verbose_name='Líder de Trabajo'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_ultimo_gasto',
            field=models.DateField(blank=True, help_text='Fecha del último gasto registrado en el proyecto', null=True, verbose_name='Fecha Último Gasto Registrado'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='gasto_operativo_real',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gastos operativos reales (materiales, mano de obra, etc.)', max_digits=12, verbose_name='Gasto Operativo Real'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto_gasto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Presupuesto específico para gastos operativos del proyecto', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto de Gasto Operativo'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='reserva_contingencia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reserva para imprevistos (% del presupuesto total)', max_digits=12, verbose_name='Reserva de Contingencia'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='equipo',
            field=models.ManyToManyField(blank=True, related_name='bitacoras_equipo', to='proyectos.colaborador'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='gasto_real',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de gastos reales ejecutados', max_digits=12, verbose_name='Gasto Real Acumulado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Presupuesto total aprobado para el proyecto', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto Total'),
        ),
    ]
