# Generated by Django 5.2.3 on 2025-07-17 13:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_add_comite_proyecto_models'),
        ('servicios', '0016_add_fecha_contractual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoServicioComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_seguimiento', models.CharField(choices=[('verde', 'Verde - Sin problemas'), ('amarillo', 'Amarillo - Requiere atención'), ('rojo', 'Rojo - Crítico'), ('azul', 'Azul - En pausa')], default='verde', max_length=20, verbose_name='Estado de Seguimiento')),
                ('avance_reportado', models.DecimalField(decimal_places=2, default=0, help_text='Avance reportado en este comité', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avance Reportado (%)')),
                ('logros_periodo', models.TextField(blank=True, help_text='Principales logros desde el último comité', verbose_name='Logros del Período')),
                ('dificultades', models.TextField(blank=True, help_text='Problemas o obstáculos identificados', verbose_name='Dificultades Encontradas')),
                ('acciones_requeridas', models.TextField(blank=True, help_text='Acciones específicas definidas en el comité', verbose_name='Acciones Requeridas')),
                ('fecha_proximo_hito', models.DateField(blank=True, help_text='Fecha del próximo hito importante', null=True, verbose_name='Fecha Próximo Hito')),
                ('requiere_decision', models.BooleanField(default=False, help_text='Marca si este servicio requiere una decisión del comité', verbose_name='Requiere Decisión')),
                ('orden_presentacion', models.PositiveIntegerField(default=1, help_text='Orden en que se presenta en el comité', verbose_name='Orden de Presentación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_servicio_actualizados', to=settings.AUTH_USER_MODEL)),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_servicios', to='proyectos.comiteproyecto')),
                ('responsable_reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_servicio_comite', to='proyectos.colaborador', verbose_name='Responsable del Reporte')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_comite', to='servicios.solicitudservicio')),
            ],
            options={
                'verbose_name': 'Seguimiento de Servicio en Comité',
                'verbose_name_plural': 'Seguimientos de Servicios en Comités',
                'ordering': ['orden_presentacion', 'servicio__numero_orden'],
                'unique_together': {('comite', 'servicio')},
            },
        ),
    ]
