# Generated by Django 5.2.3 on 2025-07-17 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0018_seguimientoserviciocomite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoExternoComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_elemento', models.CharField(choices=[('proyecto', 'Proyecto'), ('servicio', 'Servicio')], default='proyecto', max_length=20, verbose_name='Tipo de Elemento')),
                ('centro_costos', models.CharField(help_text='Centro de costos al que pertenece', max_length=100, verbose_name='Centro de Costos')),
                ('nombre_proyecto', models.CharField(help_text='Nombre descriptivo del proyecto o servicio', max_length=200, verbose_name='Nombre del Proyecto/Servicio')),
                ('observaciones', models.TextField(help_text='Información adicional sobre el elemento', verbose_name='Observaciones')),
                ('estado_seguimiento', models.CharField(choices=[('verde', 'Verde - Sin problemas'), ('amarillo', 'Amarillo - Requiere atención'), ('rojo', 'Rojo - Crítico'), ('azul', 'Azul - En pausa')], default='verde', max_length=20, verbose_name='Estado de Seguimiento')),
                ('avance_reportado', models.DecimalField(decimal_places=2, default=0, help_text='Avance reportado en este comité', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avance Reportado (%)')),
                ('fecha_proximo_hito', models.DateField(blank=True, help_text='Fecha del próximo hito importante', null=True, verbose_name='Fecha Próximo Hito')),
                ('requiere_decision', models.BooleanField(default=False, help_text='Marca si este elemento requiere una decisión del comité', verbose_name='Requiere Decisión')),
                ('orden_presentacion', models.PositiveIntegerField(default=1, help_text='Orden en que se presenta en el comité', verbose_name='Orden de Presentación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_externos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos_externos', to='proyectos.comiteproyecto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_externos_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable_reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_externos_comite', to='proyectos.colaborador', verbose_name='Responsable del Reporte')),
            ],
            options={
                'verbose_name': 'Elemento Externo de Comité',
                'verbose_name_plural': 'Elementos Externos de Comités',
                'ordering': ['orden_presentacion', 'nombre_proyecto'],
            },
        ),
    ]
