# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0019_elementoexternocomite'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoproyectocomite',
            name='tareas_generadas',
            field=models.ManyToManyField(
                to='tasks.Task',
                blank=True,
                related_name='seguimientos_comite',
                verbose_name='Tareas Generadas',
                help_text='Tareas creadas desde este seguimiento de comité'
            ),
        ),
    ]