# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_add_fields_to_elementoexterno'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementoexternocomite',
            name='tipo_elemento',
            field=models.CharField(
                choices=[('proyecto', 'Proyecto'), ('servicio', 'Servicio'), ('otros', 'Otros')],
                default='proyecto',
                max_length=20,
                verbose_name='Tipo de Elemento'
            ),
        ),
        migrations.AlterField(
            model_name='elementoexternocomite',
            name='centro_costos',
            field=models.CharField(
                blank=True,
                help_text='Centro de costos al que pertenece',
                max_length=100,
                verbose_name='Centro de Costos'
            ),
        ),
        migrations.AddField(
            model_name='elementoexternocomite',
            name='tareas_generadas',
            field=models.ManyToManyField(
                blank=True,
                help_text='Tareas creadas desde este elemento externo',
                related_name='elementos_externos_comite',
                to='tasks.task',
                verbose_name='Tareas Generadas'
            ),
        ),
    ]