# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0022_elementoexterno_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoserviciocomite',
            name='decision_tomada',
            field=models.TextField(
                verbose_name='Decisión Tomada',
                blank=True,
                help_text='Decisión específica tomada por el comité para este servicio'
            ),
        ),
    ]