# Generated by Django 5.2.3 on 2025-06-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_alter_user_options_user_cargo_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('crm', 'CRM'), ('proyectos', 'Proyectos'), ('servicios', 'Servicios'), ('mantenimiento', 'Mantenimiento'), ('insumos', 'Insumos'), ('tasks', 'Tareas'), ('users', 'Usuarios')], max_length=20, verbose_name='módulo'),
        ),
    ]
