steps:
  # Build the container image with no cache
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/rgd-aire:latest', '-t', 'gcr.io/$PROJECT_ID/rgd-aire:$SHORT_SHA', '-f', 'Dockerfile.cloudrun', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/rgd-aire']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'rgd-aire', '--image', 'gcr.io/$PROJECT_ID/rgd-aire:$SHORT_SHA', '--region', 'us-central1', '--platform', 'managed']

# Images to push
images:
  - 'gcr.io/$PROJECT_ID/rgd-aire:latest'
  - 'gcr.io/$PROJECT_ID/rgd-aire:$SHORT_SHA'

# Timeout for the entire build
timeout: '1200s'
EOF < /dev/null