services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=rgd_aire.settings_dev
      - FORCE_HTTP=true
    volumes:
      - .:/app
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"