# Generated by Django 5.2.3 on 2025-06-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='nombre_proyecto',
            field=models.CharField(blank=True, help_text='Nombre del proyecto asociado al servicio', max_length=200, verbose_name='Nombre del Proyecto'),
        ),
    ]
