# Generated by Django 5.2.3 on 2025-06-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_add_responsable_fields_to_actividad'),
        ('servicios', '0002_add_nombre_proyecto_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='cronograma',
            field=models.FileField(blank=True, help_text='Archivo del cronograma del proyecto', null=True, upload_to='servicios/cronogramas/', verbose_name='Cronograma'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='director_proyecto',
            field=models.ForeignKey(blank=True, help_text='Colaborador responsable de dirigir el proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_dirigidos', to='proyectos.colaborador', verbose_name='Director de Proyecto'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='ingeniero_residente',
            field=models.ForeignKey(blank=True, help_text='Colaborador responsable de la residencia del proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_residencia', to='proyectos.colaborador', verbose_name='Ingeniero Residente'),
        ),
    ]
