# Generated by Django 5.2.3 on 2025-06-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_trato_fecha_creacion'),
        ('servicios', '0003_add_project_team_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='cotizacion_aprobada',
            field=models.ForeignKey(blank=True, help_text='Cotización aprobada asociada al servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.versioncotizacion', verbose_name='Cotización Aprobada'),
        ),
    ]
