# Generated by Django 5.2.3 on 2025-06-18 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_trato_fecha_creacion'),
        ('servicios', '0004_solicitudservicio_cotizacion_aprobada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='trato_origen',
            field=models.ForeignKey(blank=True, help_text='Trato del CRM que originó esta solicitud de servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.trato', verbose_name='Trato de Origen'),
        ),
    ]
