# Generated by Django 5.2.3 on 2025-06-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_solicitudservicio_trato_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('inspeccion', 'Visita de Inspección'), ('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('control', 'Control'), ('mantenimiento', 'Mantenimiento')], max_length=20, verbose_name='Tipo de Servicio'),
        ),
    ]
