# Generated by Django 5.2.3 on 2025-06-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_solicitudservicio_tipo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ejecucion', 'En Ejecución'), ('atrasado', 'Atrasado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('inspeccion', 'Visita de Inspección'), ('correctivo', 'Mantenimiento Correctivo'), ('control', 'Control'), ('mantenimiento', 'Mantenimiento')], max_length=20, verbose_name='Tipo de Servicio'),
        ),
    ]
