# Generated by Django 5.2.3 on 2025-06-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_alter_solicitudservicio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('inspeccion', 'Visita de Inspección'), ('correctivo', 'Mantenimiento Correctivo')], max_length=20, verbose_name='Tipo de Servicio'),
        ),
    ]
