# Generated by Django 5.2.3 on 2025-06-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_alter_solicitudservicio_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='informetrabajo',
            name='descripcion_trabajo',
            field=models.JSONField(blank=True, default=list, help_text='Tipo de trabajo realizado', verbose_name='Descripción del Trabajo'),
        ),
    ]
