# Generated by Django 5.2.3 on 2025-06-18 18:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_informetrabajo_descripcion_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('unidad_medida', models.CharField(default='Unidad', max_length=50, verbose_name='Unidad de Medida')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_requeridos', to='servicios.informetrabajo')),
            ],
            options={
                'verbose_name': 'Material Requerido',
                'verbose_name_plural': 'Materiales Requeridos',
                'ordering': ['descripcion'],
            },
        ),
    ]
