# Generated by Django 5.2.3 on 2025-06-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_materialrequerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='informetrabajo',
            name='entregado_cliente_cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo de quien Recibe (Cliente)'),
        ),
        migrations.AddField(
            model_name='informetrabajo',
            name='entregado_cliente_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
        migrations.AddField(
            model_name='informetrabajo',
            name='entregado_cliente_firma',
            field=models.ImageField(blank=True, upload_to='firmas/recepcion/', verbose_name='Firma de quien Recibe (Cliente)'),
        ),
        migrations.AddField(
            model_name='informetrabajo',
            name='entregado_cliente_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre de quien Recibe (Cliente)'),
        ),
        migrations.AddField(
            model_name='informetrabajo',
            name='entregado_por_cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo de quien Entrega'),
        ),
        migrations.AddField(
            model_name='informetrabajo',
            name='entregado_por_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='informetrabajo',
            name='entregado_por_firma',
            field=models.ImageField(blank=True, upload_to='firmas/entrega/', verbose_name='Firma de quien Entrega'),
        ),
        migrations.AddField(
            model_name='informetrabajo',
            name='entregado_por_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre de quien Entrega'),
        ),
    ]
