# Generated by Django 5.2.3 on 2025-06-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_informetrabajo_entregado_cliente_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informetrabajo',
            name='observaciones_encuesta',
            field=models.TextField(blank=True, help_text='Comentarios adicionales del cliente sobre el servicio', verbose_name='Observaciones de la Encuesta'),
        ),
    ]
