# Generated by Django 5.2.3 on 2025-06-18 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_informetrabajo_observaciones_encuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='informes/adjuntos/%Y/%m/', verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre Original')),
                ('tipo_adjunto', models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento'), ('video', 'Video'), ('audio', 'Audio'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Adjunto')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional del adjunto', max_length=500, verbose_name='Descripción')),
                ('tamaño_archivo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='servicios.informetrabajo')),
            ],
            options={
                'verbose_name': 'Adjunto de Informe',
                'verbose_name_plural': 'Adjuntos de Informe',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
