# Generated by Django 4.2.21 on 2025-07-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_adjuntoinforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('inspeccion', 'Visita de Inspección'), ('correctivo', 'Mantenimiento Correctivo'), ('visita_servicio', 'Visita de Servicio')], max_length=20, verbose_name='Tipo de Servicio'),
        ),
    ]
