# Generated by Django 5.2.3 on 2025-07-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_alter_solicitudservicio_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='dias_prometidos',
            field=models.PositiveIntegerField(blank=True, help_text='Días prometidos del trato original', null=True, verbose_name='Promesa de Días'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='orden_contrato',
            field=models.CharField(blank=True, help_text='Orden o contrato proveniente del CRM', max_length=100, verbose_name='Orden o Contrato'),
        ),
    ]
