# Generated by Django 5.2.3 on 2025-07-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_add_orden_contrato_dias_prometidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='fecha_contractual',
            field=models.DateField(blank=True, help_text='Fecha de creación + días prometidos', null=True, verbose_name='Fecha Contractual'),
        ),
    ]
