# Generated by Django 5.2.3 on 2025-07-24 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('servicios', '0016_add_fecha_contractual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='director_proyecto',
            field=models.ForeignKey(blank=True, help_text='Colaborador responsable de dirigir el proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_dirigidos', to='colaboradores.colaborador', verbose_name='Director de Proyecto'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='ingeniero_residente',
            field=models.ForeignKey(blank=True, help_text='Colaborador responsable de la residencia del proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_residencia', to='colaboradores.colaborador', verbose_name='Ingeniero Residente'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_como_tecnico', to='colaboradores.colaborador', verbose_name='Técnico Asignado'),
        ),
        migrations.AlterField(
            model_name='ubicaciontecnico',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_como_tecnico', to='colaboradores.colaborador', verbose_name='Técnico'),
        ),
    ]
