# Generated by Django 5.2.3 on 2025-06-20 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mantenimiento', '0003_informemantenimientocoleccionpolvo'),
        ('proyectos', '0017_add_comite_proyecto_models'),
        ('servicios', '0013_adjuntoinforme'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='centro_costos',
            field=models.CharField(blank=True, help_text='Centro de costos asociado a la tarea', max_length=100, verbose_name='centro de costos'),
        ),
        migrations.AddField(
            model_name='task',
            name='contrato_mantenimiento',
            field=models.ForeignKey(blank=True, help_text='Contrato de mantenimiento relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.contratomantenimiento', verbose_name='contrato de mantenimiento'),
        ),
        migrations.AddField(
            model_name='task',
            name='proyecto_relacionado',
            field=models.ForeignKey(blank=True, help_text='Proyecto específico al que pertenece la tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto', verbose_name='proyecto relacionado'),
        ),
        migrations.AddField(
            model_name='task',
            name='solicitud_servicio',
            field=models.ForeignKey(blank=True, help_text='Solicitud de servicio relacionada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.solicitudservicio', verbose_name='solicitud de servicio'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['centro_costos'], name='tasks_task_centro__ad3f36_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['proyecto_relacionado', 'status'], name='tasks_task_proyect_6c295d_idx'),
        ),
    ]
