# Generated by Django 5.2.1 on 2025-05-22 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Cliente')),
                ('direccion_linea1', models.CharField(max_length=200, verbose_name='Dirección Línea 1')),
                ('direccion_linea2', models.CharField(blank=True, max_length=200, verbose_name='Dirección Línea 2')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado/Departamento')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rut', models.FileField(blank=True, upload_to='rut/')),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepresentanteVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Representante de Ventas',
                'verbose_name_plural': 'Representantes de Ventas',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='crm.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oferta', models.CharField(max_length=50)),
                ('documento', models.FileField(upload_to='cotizaciones/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('razon_cambio', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='TareaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oferta', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_cierre', models.DateField()),
                ('version_cotizacion', models.PositiveIntegerField(default=1)),
                ('razon_cambio', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.cotizacion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.representanteventas')),
            ],
            options={
                'verbose_name': 'Tarea de Venta',
                'verbose_name_plural': 'Tareas de Venta',
            },
        ),
        migrations.CreateModel(
            name='Trato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_trato', models.CharField(max_length=50, unique=True)),
                ('origen_lead', models.CharField(choices=[('referido', 'Referido'), ('web', 'Sitio Web'), ('llamada', 'Llamada Entrante'), ('email', 'Email'), ('otro', 'Otro')], max_length=20)),
                ('tipo_negociacion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_estimada_cierre', models.DateField()),
                ('fecha_envio_cotizacion', models.DateField(blank=True, null=True)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_oferta', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('centro_costos', models.CharField(max_length=100)),
                ('orden_compra', models.CharField(blank=True, max_length=100)),
                ('dias_prometidos', models.PositiveIntegerField()),
                ('descripcion_proyecto', models.TextField()),
                ('actualizaciones', models.TextField(blank=True)),
                ('etapa', models.CharField(choices=[('prospecto', 'Prospecto'), ('contactado', 'Contactado'), ('propuesta', 'Propuesta Enviada'), ('negociacion', 'En Negociación'), ('ganado', 'Cerrado - Ganado'), ('perdido', 'Cerrado - Perdido')], default='prospecto', max_length=20)),
                ('documentos', models.FileField(blank=True, upload_to='tratos/documentos/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cliente')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.representanteventas')),
            ],
            options={
                'verbose_name': 'Trato/Oportunidad',
                'verbose_name_plural': 'Tratos/Oportunidades',
            },
        ),
    ]
