# Generated by Django 4.2.9 on 2025-05-22 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['nombre'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='tareaventa',
            options={'ordering': ['fecha_vencimiento'], 'verbose_name': 'Tarea de Venta', 'verbose_name_plural': 'Tareas de Venta'},
        ),
        migrations.AlterModelOptions(
            name='trato',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Trato', 'verbose_name_plural': 'Tratos'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='numero_oferta',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='razon_cambio',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='version',
        ),
        migrations.RemoveField(
            model_name='representanteventas',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='representanteventas',
            name='email',
        ),
        migrations.RemoveField(
            model_name='representanteventas',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tareaventa',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='tareaventa',
            name='fecha_cierre',
        ),
        migrations.RemoveField(
            model_name='tareaventa',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='tareaventa',
            name='numero_oferta',
        ),
        migrations.RemoveField(
            model_name='tareaventa',
            name='razon_cambio',
        ),
        migrations.RemoveField(
            model_name='tareaventa',
            name='version_cotizacion',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='actualizaciones',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='centro_costos',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='descripcion_proyecto',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='dias_prometidos',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='fecha_envio_cotizacion',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='fecha_estimada_cierre',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='numero_oferta',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='numero_trato',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='orden_compra',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='origen_lead',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='representante',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='tipo_negociacion',
        ),
        migrations.RemoveField(
            model_name='trato',
            name='valor_estimado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='trato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='crm.trato'),
        ),
        migrations.AddField(
            model_name='representanteventas',
            name='meta_ventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Meta de Ventas'),
        ),
        migrations.AddField(
            model_name='representanteventas',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='representanteventas',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareaventa',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='tareaventa',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='tareaventa',
            name='tipo',
            field=models.CharField(choices=[('llamada', 'Llamada'), ('reunion', 'Reunión'), ('email', 'Email'), ('seguimiento', 'Seguimiento'), ('otro', 'Otro')], default='seguimiento', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='tareaventa',
            name='trato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='crm.trato'),
        ),
        migrations.AddField(
            model_name='trato',
            name='cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='trato',
            name='contacto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='trato',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='trato',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('cotizacion', 'Cotización Enviada'), ('negociacion', 'En Negociación'), ('ganado', 'Ganado'), ('perdido', 'Perdido'), ('cancelado', 'Cancelado')], default='nuevo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='trato',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AddField(
            model_name='trato',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='trato',
            name='fuente',
            field=models.CharField(choices=[('web', 'Sitio Web'), ('referido', 'Referido'), ('redes', 'Redes Sociales'), ('publicidad', 'Publicidad'), ('evento', 'Evento'), ('otro', 'Otro')], default='web', max_length=20, verbose_name='Fuente'),
        ),
        migrations.AddField(
            model_name='trato',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Trato'),
        ),
        migrations.AddField(
            model_name='trato',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='trato',
            name='probabilidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Probabilidad (%)'),
        ),
        migrations.AddField(
            model_name='trato',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trato',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='trato',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_linea1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección Línea 1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado/Departamento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.FileField(blank=True, upload_to='clientes/rut/', verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='crm.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='tareaventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='crm.cliente'),
        ),
        migrations.AlterField(
            model_name='tareaventa',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tareaventa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tareaventa',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trato',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
