# Generated by Django 5.2.1 on 2025-05-23 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_cliente_options_alter_contacto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trato',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tratos', to='crm.cliente', verbose_name='Cliente'),
        ),
    ]
