# Generated by Django 5.2.1 on 2025-05-23 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_trato_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaventa',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='tareaventa',
            name='titulo',
            field=models.CharField(default='Nueva Tarea', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='trato',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
    ]
