# Generated by Django 5.2.1 on 2025-05-23 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_tareaventa_prioridad_tareaventa_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trato',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
    ]
