# Generated by Django 5.2.1 on 2025-05-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_trato_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trato',
            name='centro_costos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Centro de Costos'),
        ),
        migrations.AddField(
            model_name='trato',
            name='dias_prometidos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Promesa de Días'),
        ),
        migrations.AddField(
            model_name='trato',
            name='nombre_proyecto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre Proyecto'),
        ),
        migrations.AddField(
            model_name='trato',
            name='orden_contrato',
            field=models.CharField(blank=True, max_length=100, verbose_name='Orden o Contrato'),
        ),
    ]
