# Generated by Django 5.2.1 on 2025-05-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_trato_centro_costos_trato_dias_prometidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='clientes/documentos/', verbose_name='Archivo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='crm.cliente')),
            ],
            options={
                'verbose_name': 'Documento del Cliente',
                'verbose_name_plural': 'Documentos del Cliente',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
