# Generated by Django 5.2.1 on 2025-05-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_documentocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sector_actividad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sector de Actividad'),
        ),
    ]
