# Generated by Django 5.2.1 on 2025-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_cliente_sector_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='trato',
            name='numero_oferta',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='# Oferta'),
        ),
    ]
