# Generated by Django 5.2.1 on 2025-05-23 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_trato_numero_oferta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Número de Versión')),
                ('archivo', models.FileField(upload_to='cotizaciones/versiones/', verbose_name='Archivo')),
                ('razon_cambio', models.TextField(verbose_name='Razón del Cambio')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='crm.cotizacion')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión de Cotización',
                'verbose_name_plural': 'Versiones de Cotización',
                'ordering': ['-version'],
                'unique_together': {('cotizacion', 'version')},
            },
        ),
    ]
