# Generated by Django 4.2.9 on 2025-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_tareaventa_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaventa',
            name='fecha_ejecucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ejecución'),
        ),
    ]
