# Generated by Django 5.2.1 on 2025-05-23 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_add_fecha_ejecucion_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='trato',
            name='tipo_negociacion',
            field=models.CharField(choices=[('producto', 'Venta de Producto'), ('servicio', 'Prestación de Servicio'), ('proyecto', 'Proyecto'), ('mantenimiento', 'Mantenimiento'), ('consultoria', 'Consultoría'), ('otro', 'Otro')], default='producto', max_length=20, verbose_name='Tipo de Negociación'),
        ),
        migrations.AlterField(
            model_name='trato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratos', to='crm.cliente', verbose_name='Cliente'),
        ),
    ]
