# Generated by Django 4.2.21 on 2025-06-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_trato_tipo_negociacion_alter_trato_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIT'),
        ),
    ]
