# Generated by Django 4.2.21 on 2025-06-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_cliente_nit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pais',
        ),
    ]
