# Generated by Django 4.2.21 on 2025-06-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_remove_cliente_codigo_postal_remove_cliente_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trato',
            name='estado',
            field=models.CharField(choices=[('revision_tecnica', 'Revisión Técnica'), ('elaboracion_oferta', 'Elaboración de oferta'), ('envio_negociacion', 'Envío de Oferta - Negociación'), ('formalizacion', 'Formalización'), ('ganado', 'Ganado'), ('perdido', 'Perdido'), ('sin_informacion', 'Sin información')], default='revision_tecnica', max_length=20, verbose_name='Estado'),
        ),
    ]
