# Generated by Django 4.2.21 on 2025-06-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_trato_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trato',
            name='tipo_negociacion',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('control', 'Control'), ('diseno', 'Diseño'), ('filtros', 'Filtros'), ('mantenimiento', 'Mantenimiento'), ('servicios', 'Servicios')], default='contrato', max_length=20, verbose_name='Tipo de Negociación'),
        ),
    ]
