# Generated by Django 4.2.21 on 2025-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_trato_tipo_negociacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trato',
            name='fuente',
            field=models.CharField(choices=[('visita', 'Visita'), ('informe_tecnico', 'Informe Técnico'), ('email', 'Email'), ('telefono', 'Teléfono'), ('whatsapp', 'Whatsapp'), ('otro', 'Otro')], default='visita', max_length=20, verbose_name='Fuente'),
        ),
    ]
