# Generated by Django 4.2.21 on 2025-06-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_trato_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='trato',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
    ]
