# Generated by Django 4.2.21 on 2025-06-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_cliente_direccion_alter_trato_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trato',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratos', to='crm.contacto', verbose_name='Contacto'),
        ),
    ]
