# Generated by Django 4.2.21 on 2025-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_trato_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trato',
            name='fecha_envio_cotizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Envío de Cotización'),
        ),
    ]
