# Generated by Django 4.2.21 on 2025-06-17 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_trato_fecha_envio_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trato',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
    ]
