# Generated by Django 4.2.21 on 2025-06-17 15:31

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_trato_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trato',
            name='fecha_creacion',
            field=models.DateField(default=crm.models.fecha_actual, verbose_name='Fecha de Creación'),
        ),
    ]
