# Generated by Django 4.2.21 on 2025-06-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_trato_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='camara',
            field=models.FileField(blank=True, upload_to='clientes/camara/', verbose_name='Cámara de Comercio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.FileField(blank=True, upload_to='clientes/cedula/', verbose_name='Cédula de Ciudadanía'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ef',
            field=models.FileField(blank=True, upload_to='clientes/ef/', verbose_name='Estados Financieros'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='formulario_vinculacion',
            field=models.FileField(blank=True, upload_to='clientes/vinculacion/', verbose_name='Formulario de Vinculación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sector_actividad',
            field=models.CharField(blank=True, choices=[('agricultura', 'Agricultura'), ('alimentos_bebidas', 'Alimentos y Bebidas'), ('construccion', 'Construcción'), ('educacion', 'Educación'), ('energia', 'Energía'), ('farmaceutico', 'Farmacéutico'), ('financiero', 'Financiero'), ('manufactura', 'Manufactura'), ('mineria', 'Minería'), ('petroleo_gas', 'Petróleo y Gas'), ('quimico', 'Químico'), ('salud', 'Salud'), ('tecnologia', 'Tecnología'), ('textil', 'Textil'), ('transporte', 'Transporte'), ('turismo', 'Turismo'), ('otro', 'Otro')], max_length=100, verbose_name='Sector de Actividad'),
        ),
    ]
