# Generated by Django 4.2.21 on 2025-06-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_cliente_camara_cliente_cedula_cliente_ef_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareaventa',
            name='prioridad',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sector_actividad',
            field=models.CharField(blank=True, choices=[('alimentos', 'Alimentos'), ('comercio', 'Comercio'), ('construccion', 'Construcción'), ('cosmeticos', 'Cosméticos'), ('educacion', 'Educación'), ('farmaceutico', 'Farmacéutico'), ('fitoterapeuta', 'Fitoterapeuta'), ('industrial', 'Industrial'), ('infraestructura', 'Infraestructura'), ('salud', 'Salud'), ('servicios_financieros', 'Servicios Financieros')], max_length=100, verbose_name='Sector de Actividad'),
        ),
        migrations.AlterField(
            model_name='tareaventa',
            name='tipo',
            field=models.CharField(choices=[('llamada', 'Llamada'), ('reunion', 'Reunión'), ('email', 'Email'), ('seguimiento', 'Seguimiento'), ('modificacion', 'Modificación'), ('otro', 'Otro')], default='seguimiento', max_length=20, verbose_name='Tipo'),
        ),
    ]
