# Generated by Django 4.2.21 on 2025-06-19 17:42

import crm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0026_alter_tareaventa_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('sector_actividad', models.CharField(blank=True, choices=[('alimentos', 'Alimentos'), ('comercio', 'Comercio'), ('construccion', 'Construcción'), ('cosmeticos', 'Cosméticos'), ('educacion', 'Educación'), ('farmaceutico', 'Farmacéutico'), ('fitoterapeuta', 'Fitoterapeuta'), ('industrial', 'Industrial'), ('infraestructura', 'Infraestructura'), ('salud', 'Salud'), ('servicios_financieros', 'Servicios Financieros')], max_length=100, verbose_name='Sector de Actividad')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('calificado', 'Calificado'), ('propuesta', 'Propuesta Enviada'), ('negociacion', 'En Negociación'), ('convertido', 'Convertido'), ('perdido', 'Perdido'), ('descalificado', 'Descalificado')], default='nuevo', max_length=20, verbose_name='Estado')),
                ('fuente', models.CharField(choices=[('web', 'Página Web'), ('referido', 'Referido'), ('publicidad', 'Publicidad'), ('evento', 'Evento'), ('llamada_fria', 'Llamada Fría'), ('email', 'Email Marketing'), ('redes_sociales', 'Redes Sociales'), ('otro', 'Otro')], default='web', max_length=20, verbose_name='Fuente')),
                ('nivel_interes', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy Alto')], default='medio', max_length=20, verbose_name='Nivel de Interés')),
                ('necesidad', models.TextField(blank=True, verbose_name='Necesidad/Problema')),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto Estimado')),
                ('fecha_contacto_inicial', models.DateField(default=crm.models.fecha_actual, verbose_name='Fecha de Contacto Inicial')),
                ('fecha_ultima_interaccion', models.DateField(default=crm.models.fecha_actual, verbose_name='Última Interacción')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('convertido_a_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_origen', to='crm.cliente')),
                ('convertido_a_trato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_origen', to='crm.trato')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
