# Generated by Django 5.2.3 on 2025-06-20 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siguiente_numero', models.PositiveIntegerField(default=1, help_text='El próximo número que se asignará a una nueva oferta', verbose_name='Siguiente Número de Oferta')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de Oferta',
                'verbose_name_plural': 'Configuración de Ofertas',
            },
        ),
    ]
