# Generated by Django 5.2.3 on 2025-07-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_configuracionoferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trato',
            name='tipo_negociacion',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('servicios', 'Servicios'), ('mantenimiento', 'Mantenimiento'), ('suministro', 'Suministro')], default='contrato', max_length=20, verbose_name='Tipo de Negociación'),
        ),
    ]
