# Generated by Django 5.2.3 on 2025-07-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_alter_trato_tipo_negociacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trato',
            name='subclasificacion_comercial',
            field=models.CharField(blank=True, choices=[('filtros', 'FILTROS'), ('cartuchos', 'CARTUCHOS'), ('suministros_varios', 'SUMINISTROS VARIOS'), ('control', 'CONTROL'), ('sensores', 'SENSORES'), ('montaje_menor', 'MONTAJE MENOR'), ('mantenimiento_menor', 'MANTENIMIENTO MENOR')], max_length=30, verbose_name='Subclasificación Comercial'),
        ),
    ]
