# Generated by Django 5.2.3 on 2025-06-20 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('tipo_solicitud', models.CharField(choices=[('modificacion', 'Modificación'), ('nueva_funcionalidad', 'Nueva Funcionalidad'), ('problema', 'Problema/Error'), ('mejora', 'Mejora de Rendimiento'), ('otro', 'Otro')], max_length=20, verbose_name='tipo de solicitud')),
                ('modulo_afectado', models.CharField(choices=[('crm', 'CRM'), ('proyectos', 'Proyectos'), ('servicios', 'Servicios'), ('mantenimiento', 'Mantenimiento'), ('insumos', 'Insumos'), ('users', 'Usuarios'), ('general', 'General')], max_length=20, verbose_name='módulo afectado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='prioridad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('en_desarrollo', 'En Desarrollo'), ('completada', 'Completada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='fecha de solicitud')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de asignación')),
                ('fecha_estimada_completado', models.DateField(blank=True, null=True, verbose_name='fecha estimada completado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='fecha completado')),
                ('pasos_reproducir', models.TextField(blank=True, help_text='Para problemas/errores, describe los pasos para reproducir el issue', verbose_name='pasos para reproducir')),
                ('impacto_negocio', models.TextField(blank=True, help_text='Describe cómo afecta esta solicitud al negocio', verbose_name='impacto en el negocio')),
                ('solucion_propuesta', models.TextField(blank=True, help_text='Si tienes una idea de solución, compártela', verbose_name='solución propuesta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha actualización')),
                ('numero_solicitud', models.CharField(blank=True, max_length=20, unique=True, verbose_name='número de solicitud')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='asignado a')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Mejora',
                'verbose_name_plural': 'Solicitudes de Mejora',
                'ordering': ['-fecha_solicitud'],
                'permissions': [('can_assign_requests', 'Puede asignar solicitudes'), ('can_change_status', 'Puede cambiar estado'), ('can_view_all_requests', 'Puede ver todas las solicitudes')],
            },
        ),
        migrations.CreateModel(
            name='ComentarioSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='comentario')),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True, verbose_name='fecha comentario')),
                ('es_interno', models.BooleanField(default=False, help_text='Los comentarios internos solo son visibles para administradores', verbose_name='comentario interno')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='mejora_continua.solicitudmejora', verbose_name='solicitud')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha_comentario'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='mejora_continua/adjuntos/', verbose_name='archivo')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='fecha subida')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='mejora_continua.solicitudmejora', verbose_name='solicitud')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['fecha_subida'],
            },
        ),
    ]
